from __future__ import annotations

import json
import os
import subprocess
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone
from typing import Any, Iterator
from urllib.parse import quote, urlsplit, urlunsplit

from .env import env_value

JOB_STALE_AFTER_SECONDS = 30 * 60
LEGACY_JOB_STALE_AFTER_SECONDS = 15 * 60
POSTGRES_INIT_LOCK_KEY = 7240185732501


POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS obsidian_notes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  frontmatter_json TEXT NOT NULL DEFAULT '{}',
  tags_json TEXT NOT NULL DEFAULT '[]',
  sha256 TEXT NOT NULL,
  mtime REAL NOT NULL,
  indexed_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS knowledge_documents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type TEXT NOT NULL,
  source_uri TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL DEFAULT '',
  raw_content TEXT NOT NULL DEFAULT '',
  content_hash TEXT NOT NULL DEFAULT '',
  metadata_json TEXT NOT NULL DEFAULT '{}',
  indexed_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS research_chunks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_id INTEGER REFERENCES obsidian_notes(id) ON DELETE CASCADE,
  document_id INTEGER REFERENCES knowledge_documents(id) ON DELETE CASCADE,
  chunk_index INTEGER NOT NULL,
  heading TEXT NOT NULL DEFAULT '',
  text TEXT NOT NULL,
  token_count INTEGER NOT NULL DEFAULT 0,
  source TEXT NOT NULL DEFAULT 'obsidian',
  created_at TEXT NOT NULL,
  UNIQUE(note_id, chunk_index),
  UNIQUE(document_id, chunk_index)
);

CREATE TABLE IF NOT EXISTS chunk_embeddings (
  chunk_id INTEGER PRIMARY KEY REFERENCES research_chunks(id) ON DELETE CASCADE,
  model TEXT NOT NULL,
  embedding_json TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS arxiv_papers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  arxiv_id TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  authors_json TEXT NOT NULL DEFAULT '[]',
  summary TEXT NOT NULL,
  categories_json TEXT NOT NULL DEFAULT '[]',
  published_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  link TEXT NOT NULL,
  pdf_link TEXT NOT NULL DEFAULT '',
  pdf_path TEXT NOT NULL DEFAULT '',
  text_path TEXT NOT NULL DEFAULT '',
  text_extracted_at TEXT,
  text_status TEXT NOT NULL DEFAULT 'pending',
  text_error TEXT NOT NULL DEFAULT '',
  text_char_count INTEGER NOT NULL DEFAULT 0,
  fetched_batch_id TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS arxiv_paper_tombstones (
  arxiv_id TEXT PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  authors_json TEXT NOT NULL DEFAULT '[]',
  summary TEXT NOT NULL DEFAULT '',
  categories_json TEXT NOT NULL DEFAULT '[]',
  published_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  link TEXT NOT NULL DEFAULT '',
  pdf_link TEXT NOT NULL DEFAULT '',
  reason TEXT NOT NULL DEFAULT 'no_match',
  original_fetched_batch_id TEXT NOT NULL DEFAULT '',
  seen_count INTEGER NOT NULL DEFAULT 0,
  last_seen_at TEXT,
  tombstoned_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS arxiv_text_chunks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paper_id INTEGER NOT NULL REFERENCES arxiv_papers(id) ON DELETE CASCADE,
  chunk_index INTEGER NOT NULL,
  source TEXT NOT NULL DEFAULT 'full_text',
  page_start INTEGER,
  page_end INTEGER,
  text TEXT NOT NULL,
  token_count INTEGER NOT NULL DEFAULT 0,
  char_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  UNIQUE(paper_id, chunk_index)
);

CREATE TABLE IF NOT EXISTS arxiv_chunk_embeddings (
  arxiv_chunk_id INTEGER PRIMARY KEY REFERENCES arxiv_text_chunks(id) ON DELETE CASCADE,
  model TEXT NOT NULL,
  embedding_json TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS arxiv_paper_embeddings (
  paper_id INTEGER NOT NULL REFERENCES arxiv_papers(id) ON DELETE CASCADE,
  model TEXT NOT NULL,
  embedding_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY(paper_id, model)
);

CREATE TABLE IF NOT EXISTS papers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canonical_key TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  authors_json TEXT NOT NULL DEFAULT '[]',
  abstract TEXT NOT NULL DEFAULT '',
  published_at TEXT NOT NULL DEFAULT '',
  year INTEGER,
  venue TEXT NOT NULL DEFAULT '',
  doi TEXT NOT NULL DEFAULT '',
  arxiv_id TEXT NOT NULL DEFAULT '',
  library_status TEXT NOT NULL DEFAULT 'candidate',
  reading_state TEXT NOT NULL DEFAULT 'unread',
  user_tags_json TEXT NOT NULL DEFAULT '[]',
  user_note TEXT NOT NULL DEFAULT '',
  saved_at TEXT,
  last_read_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS paper_sources (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paper_id INTEGER NOT NULL REFERENCES papers(id) ON DELETE CASCADE,
  source_type TEXT NOT NULL,
  source_identifier TEXT NOT NULL DEFAULT '',
  source_url TEXT NOT NULL DEFAULT '',
  metadata_json TEXT NOT NULL DEFAULT '{}',
  fetched_batch_id TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(paper_id, source_type, source_identifier)
);

CREATE TABLE IF NOT EXISTS paper_assets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paper_id INTEGER NOT NULL REFERENCES papers(id) ON DELETE CASCADE,
  asset_type TEXT NOT NULL,
  path TEXT NOT NULL DEFAULT '',
  url TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending',
  error_message TEXT NOT NULL DEFAULT '',
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS paper_chunks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paper_id INTEGER NOT NULL REFERENCES papers(id) ON DELETE CASCADE,
  asset_id INTEGER REFERENCES paper_assets(id) ON DELETE SET NULL,
  chunk_index INTEGER NOT NULL,
  source TEXT NOT NULL DEFAULT 'full_text',
  page_start INTEGER,
  page_end INTEGER,
  text TEXT NOT NULL,
  token_count INTEGER NOT NULL DEFAULT 0,
  char_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  UNIQUE(paper_id, asset_id, chunk_index)
);

CREATE TABLE IF NOT EXISTS paper_prefilter_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paper_id INTEGER NOT NULL REFERENCES arxiv_papers(id) ON DELETE CASCADE,
  model TEXT NOT NULL,
  score REAL NOT NULL,
  rank INTEGER NOT NULL,
  passed INTEGER NOT NULL,
  reason TEXT NOT NULL,
  top_chunks_json TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS matches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paper_id INTEGER NOT NULL REFERENCES arxiv_papers(id) ON DELETE CASCADE,
  arxiv_chunk_id INTEGER,
  chunk_id INTEGER NOT NULL REFERENCES research_chunks(id) ON DELETE CASCADE,
  score REAL NOT NULL,
  searchers_json TEXT NOT NULL DEFAULT '[]',
  evidence_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  UNIQUE(paper_id, chunk_id)
);

CREATE TABLE IF NOT EXISTS user_feedback (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paper_id INTEGER NOT NULL REFERENCES arxiv_papers(id) ON DELETE CASCADE,
  status TEXT NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(paper_id, status)
);

CREATE TABLE IF NOT EXISTS job_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_type TEXT NOT NULL,
  status TEXT NOT NULL,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  message TEXT NOT NULL DEFAULT '',
  pid INTEGER,
  heartbeat_at TEXT,
  meta_json TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS worker_jobs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_run_id INTEGER REFERENCES job_runs(id) ON DELETE SET NULL,
  job_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued',
  priority INTEGER NOT NULL DEFAULT 0,
  payload_json TEXT NOT NULL DEFAULT '{}',
  result_json TEXT NOT NULL DEFAULT '{}',
  error_message TEXT NOT NULL DEFAULT '',
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 1,
  run_after TEXT,
  locked_by TEXT NOT NULL DEFAULT '',
  locked_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  started_at TEXT,
  finished_at TEXT
);

CREATE TABLE IF NOT EXISTS app_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  payload_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  published_at TEXT
);

CREATE TABLE IF NOT EXISTS daily_run_meta (
  job_id INTEGER PRIMARY KEY REFERENCES job_runs(id) ON DELETE CASCADE,
  source_job_id INTEGER REFERENCES job_runs(id) ON DELETE SET NULL,
  arxiv_batch_id TEXT NOT NULL DEFAULT '',
  mode TEXT NOT NULL DEFAULT 'run-daily',
  settings_hash TEXT NOT NULL DEFAULT '',
  searchers_json TEXT NOT NULL DEFAULT '[]',
  embedding_model TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS daily_run_steps (
  job_id INTEGER NOT NULL REFERENCES job_runs(id) ON DELETE CASCADE,
  step_key TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  started_at TEXT,
  finished_at TEXT,
  error TEXT NOT NULL DEFAULT '',
  meta_json TEXT NOT NULL DEFAULT '{}',
  PRIMARY KEY(job_id, step_key)
);

CREATE TABLE IF NOT EXISTS daily_run_papers (
  job_id INTEGER NOT NULL REFERENCES job_runs(id) ON DELETE CASCADE,
  paper_id INTEGER NOT NULL REFERENCES arxiv_papers(id) ON DELETE CASCADE,
  source TEXT NOT NULL DEFAULT 'new_arxiv',
  retry_reason TEXT NOT NULL DEFAULT '',
  published_at TEXT NOT NULL DEFAULT '',
  prefilter_score REAL,
  prefilter_rank INTEGER,
  prefilter_passed INTEGER NOT NULL DEFAULT 0,
  selected INTEGER NOT NULL DEFAULT 0,
  selection_reason TEXT NOT NULL DEFAULT '',
  text_status TEXT NOT NULL DEFAULT 'pending',
  embedding_status TEXT NOT NULL DEFAULT 'pending',
  global_match_status TEXT NOT NULL DEFAULT 'pending',
  project_match_status TEXT NOT NULL DEFAULT 'pending',
  judgment_status TEXT NOT NULL DEFAULT 'pending',
  recommendation_status TEXT NOT NULL DEFAULT 'pending',
  report_status TEXT NOT NULL DEFAULT 'pending',
  archive_status TEXT NOT NULL DEFAULT 'pending',
  error TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL,
  PRIMARY KEY(job_id, paper_id)
);

CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value_json TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS research_projects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  summary TEXT NOT NULL DEFAULT '',
  goals TEXT NOT NULL DEFAULT '',
  keywords_json TEXT NOT NULL DEFAULT '[]',
  obsidian_project_path TEXT NOT NULL DEFAULT '',
  obsidian_output_dir TEXT NOT NULL DEFAULT '',
  obsidian_note_id INTEGER,
  obsidian_folder TEXT NOT NULL DEFAULT '',
  obsidian_status_tag TEXT NOT NULL DEFAULT '',
  discovery_source TEXT NOT NULL DEFAULT 'manual',
  source_tags_json TEXT NOT NULL DEFAULT '[]',
  arxiv_categories_json TEXT NOT NULL DEFAULT '[]',
  automation_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS project_papers (
  project_id INTEGER NOT NULL REFERENCES research_projects(id) ON DELETE CASCADE,
  paper_id INTEGER NOT NULL REFERENCES arxiv_papers(id) ON DELETE CASCADE,
  relation TEXT NOT NULL DEFAULT 'candidate',
  note TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(project_id, paper_id)
);

CREATE TABLE IF NOT EXISTS project_context_documents (
  project_id INTEGER NOT NULL REFERENCES research_projects(id) ON DELETE CASCADE,
  document_id INTEGER NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
  relation TEXT NOT NULL DEFAULT 'source',
  weight REAL NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(project_id, document_id, relation)
);

CREATE TABLE IF NOT EXISTS project_paper_matches (
  project_id INTEGER NOT NULL REFERENCES research_projects(id) ON DELETE CASCADE,
  paper_id INTEGER NOT NULL REFERENCES arxiv_papers(id) ON DELETE CASCADE,
  score REAL NOT NULL,
  rank_score REAL NOT NULL DEFAULT 0,
  quality_score REAL NOT NULL DEFAULT 0,
  best_arxiv_chunk_id INTEGER REFERENCES arxiv_text_chunks(id) ON DELETE SET NULL,
  best_obsidian_chunk_id INTEGER REFERENCES research_chunks(id) ON DELETE SET NULL,
  searchers_json TEXT NOT NULL DEFAULT '[]',
  evidence_json TEXT NOT NULL DEFAULT '{}',
  match_type TEXT NOT NULL DEFAULT 'project_context',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(project_id, paper_id)
);

CREATE TABLE IF NOT EXISTS project_paper_judgments (
  project_id INTEGER NOT NULL REFERENCES research_projects(id) ON DELETE CASCADE,
  paper_id INTEGER NOT NULL REFERENCES arxiv_papers(id) ON DELETE CASCADE,
  relation_type TEXT NOT NULL DEFAULT 'none',
  relevance_score REAL NOT NULL DEFAULT 0,
  usefulness_score REAL NOT NULL DEFAULT 0,
  confidence REAL NOT NULL DEFAULT 0,
  suggested_action TEXT NOT NULL DEFAULT 'ignore',
  reason TEXT NOT NULL DEFAULT '',
  evidence_mapping_json TEXT NOT NULL DEFAULT '[]',
  missing_evidence TEXT NOT NULL DEFAULT '',
  input_hash TEXT NOT NULL DEFAULT '',
  prompt_version TEXT NOT NULL DEFAULT '',
  raw_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(project_id, paper_id)
);

CREATE TABLE IF NOT EXISTS project_paper_recommendations (
  project_id INTEGER NOT NULL REFERENCES research_projects(id) ON DELETE CASCADE,
  paper_id INTEGER NOT NULL REFERENCES arxiv_papers(id) ON DELETE CASCADE,
  state TEXT NOT NULL DEFAULT 'pending',
  importance TEXT NOT NULL DEFAULT '',
  relation_type TEXT NOT NULL DEFAULT 'indirect',
  reason TEXT NOT NULL DEFAULT '',
  obsidian_path TEXT NOT NULL DEFAULT '',
  attachment_path TEXT NOT NULL DEFAULT '',
  source_judgment_hash TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  synced_at TEXT,
  PRIMARY KEY(project_id, paper_id)
);

CREATE TABLE IF NOT EXISTS paper_reader_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paper_id INTEGER NOT NULL REFERENCES arxiv_papers(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'chat',
  model_provider_id TEXT NOT NULL DEFAULT '',
  model TEXT NOT NULL DEFAULT '',
  context_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS paper_reader_reference_papers (
  paper_id INTEGER NOT NULL REFERENCES arxiv_papers(id) ON DELETE CASCADE,
  reference_paper_id INTEGER NOT NULL REFERENCES arxiv_papers(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(paper_id, reference_paper_id),
  CHECK(paper_id != reference_paper_id)
);

CREATE TABLE IF NOT EXISTS project_notes (
  project_id INTEGER NOT NULL REFERENCES research_projects(id) ON DELETE CASCADE,
  note_id INTEGER NOT NULL REFERENCES obsidian_notes(id) ON DELETE CASCADE,
  relation TEXT NOT NULL DEFAULT 'source',
  note TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(project_id, note_id)
);

CREATE TABLE IF NOT EXISTS artifacts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_type TEXT NOT NULL,
  scope_id INTEGER,
  artifact_type TEXT NOT NULL,
  title TEXT NOT NULL,
  content_markdown TEXT NOT NULL DEFAULT '',
  content_json TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'draft',
  source_json TEXT NOT NULL DEFAULT '{}',
  model_provider_id TEXT NOT NULL DEFAULT '',
  model TEXT NOT NULL DEFAULT '',
  input_hash TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_knowledge_documents_source ON knowledge_documents(source_type, source_uri);
CREATE INDEX IF NOT EXISTS idx_research_chunks_note ON research_chunks(note_id);
CREATE INDEX IF NOT EXISTS idx_research_chunks_document ON research_chunks(document_id, chunk_index);
CREATE INDEX IF NOT EXISTS idx_arxiv_papers_published ON arxiv_papers(published_at);
CREATE INDEX IF NOT EXISTS idx_arxiv_paper_tombstones_reason ON arxiv_paper_tombstones(reason, tombstoned_at DESC);
CREATE INDEX IF NOT EXISTS idx_arxiv_text_chunks_paper ON arxiv_text_chunks(paper_id, chunk_index);
CREATE INDEX IF NOT EXISTS idx_papers_status ON papers(library_status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_papers_arxiv_id ON papers(arxiv_id);
CREATE INDEX IF NOT EXISTS idx_paper_sources_paper ON paper_sources(paper_id, source_type);
CREATE INDEX IF NOT EXISTS idx_paper_assets_paper ON paper_assets(paper_id, asset_type);
CREATE INDEX IF NOT EXISTS idx_paper_chunks_paper ON paper_chunks(paper_id, chunk_index);
CREATE INDEX IF NOT EXISTS idx_paper_prefilter_runs_paper ON paper_prefilter_runs(paper_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_matches_paper_score ON matches(paper_id, score DESC);
CREATE INDEX IF NOT EXISTS idx_worker_jobs_claim ON worker_jobs(status, priority DESC, run_after, id);
CREATE INDEX IF NOT EXISTS idx_worker_jobs_job_run ON worker_jobs(job_run_id);
CREATE INDEX IF NOT EXISTS idx_app_events_unpublished ON app_events(published_at, id);
CREATE INDEX IF NOT EXISTS idx_daily_run_meta_mode ON daily_run_meta(mode, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_daily_run_steps_status ON daily_run_steps(job_id, status);
CREATE INDEX IF NOT EXISTS idx_daily_run_papers_selected ON daily_run_papers(job_id, selected, prefilter_rank);
CREATE INDEX IF NOT EXISTS idx_daily_run_papers_stage ON daily_run_papers(job_id, text_status, global_match_status, project_match_status);
CREATE INDEX IF NOT EXISTS idx_daily_run_papers_paper ON daily_run_papers(paper_id);
CREATE INDEX IF NOT EXISTS idx_research_projects_status ON research_projects(status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_research_projects_obsidian_note ON research_projects(obsidian_note_id);
CREATE INDEX IF NOT EXISTS idx_project_context_documents_document ON project_context_documents(document_id);
CREATE INDEX IF NOT EXISTS idx_project_paper_matches_project_score ON project_paper_matches(project_id, score DESC);
CREATE INDEX IF NOT EXISTS idx_project_paper_matches_paper ON project_paper_matches(paper_id);
CREATE INDEX IF NOT EXISTS idx_project_paper_judgments_project_action ON project_paper_judgments(project_id, suggested_action, confidence DESC);
CREATE INDEX IF NOT EXISTS idx_project_paper_judgments_paper ON project_paper_judgments(paper_id);
CREATE INDEX IF NOT EXISTS idx_project_paper_recommendations_state ON project_paper_recommendations(state, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_project_paper_recommendations_paper ON project_paper_recommendations(paper_id);
CREATE INDEX IF NOT EXISTS idx_paper_reader_messages_paper ON paper_reader_messages(paper_id, id);
CREATE INDEX IF NOT EXISTS idx_paper_reader_reference_papers ON paper_reader_reference_papers(paper_id, position);
CREATE INDEX IF NOT EXISTS idx_artifacts_scope ON artifacts(scope_type, scope_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_artifacts_type ON artifacts(artifact_type, updated_at DESC);
"""

REQUIRED_TABLES = {
    "obsidian_notes",
    "knowledge_documents",
    "research_chunks",
    "chunk_embeddings",
    "arxiv_papers",
    "arxiv_paper_tombstones",
    "arxiv_text_chunks",
    "arxiv_chunk_embeddings",
    "arxiv_paper_embeddings",
    "papers",
    "paper_sources",
    "paper_assets",
    "paper_chunks",
    "paper_prefilter_runs",
    "matches",
    "user_feedback",
    "job_runs",
    "worker_jobs",
    "app_events",
    "daily_run_meta",
    "daily_run_steps",
    "daily_run_papers",
    "app_settings",
    "research_projects",
    "project_papers",
    "project_context_documents",
    "project_paper_matches",
    "project_paper_judgments",
    "project_paper_recommendations",
    "paper_reader_messages",
    "paper_reader_reference_papers",
    "project_notes",
    "artifacts",
}

REQUIRED_INDEXES = {
    "idx_knowledge_documents_source",
    "idx_research_chunks_note",
    "idx_research_chunks_document",
    "idx_arxiv_papers_published",
    "idx_arxiv_paper_tombstones_reason",
    "idx_arxiv_text_chunks_paper",
    "idx_papers_status",
    "idx_papers_arxiv_id",
    "idx_paper_sources_paper",
    "idx_paper_assets_paper",
    "idx_paper_chunks_paper",
    "idx_paper_prefilter_runs_paper",
    "idx_matches_paper_score",
    "idx_worker_jobs_claim",
    "idx_worker_jobs_job_run",
    "idx_app_events_unpublished",
    "idx_daily_run_meta_mode",
    "idx_daily_run_steps_status",
    "idx_daily_run_papers_selected",
    "idx_daily_run_papers_stage",
    "idx_daily_run_papers_paper",
    "idx_research_projects_status",
    "idx_research_projects_obsidian_note",
    "idx_project_context_documents_document",
    "idx_project_paper_matches_project_score",
    "idx_project_paper_matches_paper",
    "idx_project_paper_judgments_project_action",
    "idx_project_paper_judgments_paper",
    "idx_project_paper_recommendations_state",
    "idx_project_paper_recommendations_paper",
    "idx_paper_reader_messages_paper",
    "idx_paper_reader_reference_papers",
    "idx_artifacts_scope",
    "idx_artifacts_type",
}

POSTGRES_REQUIRED_INDEXES = REQUIRED_INDEXES | {
    "idx_research_chunks_document_unique",
    "idx_matches_unique_paper_chunk",
    "idx_user_feedback_unique_paper_status",
    "idx_project_notes_unique_project_note",
    "idx_project_context_documents_unique",
    "idx_paper_sources_unique",
    "idx_paper_chunks_unique",
}

REQUIRED_COLUMNS = {
    "research_chunks": {"document_id"},
    "arxiv_papers": {
        "pdf_path",
        "text_path",
        "text_extracted_at",
        "text_status",
        "text_error",
        "text_char_count",
    },
    "matches": {"arxiv_chunk_id"},
    "project_paper_matches": {"rank_score", "quality_score"},
    "research_projects": {
        "obsidian_project_path",
        "obsidian_output_dir",
        "obsidian_note_id",
        "obsidian_folder",
        "obsidian_status_tag",
        "discovery_source",
        "source_tags_json",
        "arxiv_categories_json",
        "automation_json",
    },
    "project_paper_recommendations": {
        "importance",
        "relation_type",
        "reason",
        "obsidian_path",
        "attachment_path",
        "source_judgment_hash",
        "synced_at",
    },
    "paper_reader_messages": {"context_json"},
    "job_runs": {
        "pid",
        "heartbeat_at",
    },
    "worker_jobs": {
        "job_run_id",
        "job_type",
        "status",
        "priority",
        "payload_json",
        "result_json",
        "error_message",
        "attempts",
        "max_attempts",
        "run_after",
        "locked_by",
        "locked_at",
        "created_at",
        "updated_at",
        "started_at",
        "finished_at",
    },
    "app_events": {
        "event_type",
        "payload_json",
        "created_at",
        "published_at",
    },
    "daily_run_meta": {
        "source_job_id",
        "arxiv_batch_id",
        "mode",
        "settings_hash",
        "searchers_json",
        "embedding_model",
        "created_at",
    },
    "daily_run_steps": {
        "status",
        "started_at",
        "finished_at",
        "error",
        "meta_json",
    },
    "daily_run_papers": {
        "source",
        "retry_reason",
        "published_at",
        "prefilter_score",
        "prefilter_rank",
        "prefilter_passed",
        "selected",
        "selection_reason",
        "text_status",
        "embedding_status",
        "global_match_status",
        "project_match_status",
        "judgment_status",
        "recommendation_status",
        "report_status",
        "archive_status",
        "error",
        "updated_at",
    },
}

OBSOLETE_TABLES = {"llm_explanations", "paper_reading_reports", "project_artifacts"}


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def clean_unicode(value: Any) -> Any:
    if isinstance(value, str):
        try:
            text = value.encode("utf-16", "surrogatepass").decode("utf-16")
        except UnicodeError:
            text = value
        return text.encode("utf-8", "replace").decode("utf-8").replace("\x00", "")
    if isinstance(value, list):
        return [clean_unicode(item) for item in value]
    if isinstance(value, tuple):
        return tuple(clean_unicode(item) for item in value)
    if isinstance(value, dict):
        return {
            clean_unicode(key): clean_unicode(item)
            for key, item in value.items()
        }
    return value


def to_json(value: Any) -> str:
    return json.dumps(clean_unicode(value), ensure_ascii=False, sort_keys=True)


def from_json(value: str | None, default: Any) -> Any:
    if not value:
        return default
    try:
        return clean_unicode(json.loads(value))
    except json.JSONDecodeError:
        return default


def _redacted_database_url(url: str) -> str:
    cleaned = str(url or "").strip().strip("'\"")
    if not cleaned:
        return "postgres"
    parsed = urlsplit(cleaned)
    if not parsed.scheme or not parsed.netloc:
        return "postgres"
    host = parsed.hostname or ""
    try:
        port = f":{parsed.port}" if parsed.port else ""
    except ValueError:
        port = ""
    userinfo = f"{parsed.username}:***@" if parsed.username else ""
    return urlunsplit((parsed.scheme, f"{userinfo}{host}{port}", parsed.path, "", ""))


def database_target() -> dict[str, str]:
    target = _redacted_database_url(database_url_from_env())
    return {"dialect": "postgres", "target": target, "path": target}


def _postgres_schema_lines(include_indexes: bool) -> list[str]:
    lines = POSTGRES_SCHEMA.splitlines()
    if not include_indexes:
        lines = [
            line
            for line in lines
            if not line.strip().upper().startswith("CREATE INDEX ")
        ]
    return lines


def postgres_schema_sql(include_indexes: bool = True) -> str:
    return "\n".join(_postgres_schema_lines(include_indexes))


def postgres_index_sql() -> str:
    lines = [
        line
        for line in _postgres_schema_lines(include_indexes=True)
        if line.strip().upper().startswith("CREATE INDEX ")
    ]
    return "\n".join(lines)


def database_url_from_env() -> str:
    configured = env_value("DATABASE_URL", "").strip()
    if configured:
        return configured

    host = env_value("POSTGRES_HOST", "").strip()
    if not host:
        return ""
    port = env_value("POSTGRES_PORT", "5432").strip() or "5432"
    user = env_value("POSTGRES_USER", "research_app").strip()
    password = env_value("POSTGRES_PASSWORD", "").strip()
    database = env_value("POSTGRES_DB", "research_intelligence").strip()
    return (
        f"postgresql://{quote(user, safe='')}:{quote(password, safe='')}@"
        f"{host}:{port}/{quote(database, safe='')}"
    )


def connect():
    database_url = database_url_from_env()
    if not database_url:
        raise RuntimeError(
            "PostgreSQL is required. Set DATABASE_URL/DATABASE_URL_FILE or POSTGRES_HOST, "
            "POSTGRES_DB, POSTGRES_USER, and POSTGRES_PASSWORD/POSTGRES_PASSWORD_FILE."
        )
    from .pg import connect_postgres

    return connect_postgres(database_url)


def init_db(conn) -> None:
    if getattr(conn, "dialect", "") != "postgres":
        raise RuntimeError("PostgreSQL connection required")
    if _postgres_schema_current(conn):
        conn.commit()
        return
    try:
        conn.execute("SELECT pg_advisory_xact_lock(?)", (POSTGRES_INIT_LOCK_KEY,))
        if _postgres_schema_current(conn):
            conn.commit()
            return
        conn.executescript(postgres_schema_sql(include_indexes=False))
        _migrate_postgres_db(conn)
        conn.executescript(postgres_index_sql())
        conn.commit()
    except Exception:
        try:
            conn.rollback()
        except Exception:
            pass
        raise


def _postgres_columns(conn, table: str) -> dict[str, dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT column_name, is_nullable
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = ?
        """,
        (table,),
    ).fetchall()
    return {str(row["column_name"]): {"is_nullable": str(row["is_nullable"])} for row in rows}


def _postgres_names(conn, object_type: str) -> set[str]:
    if object_type == "table":
        rows = conn.execute(
            """
            SELECT table_name AS name
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_type = 'BASE TABLE'
            """
        ).fetchall()
    elif object_type == "index":
        rows = conn.execute(
            """
            SELECT indexname AS name
            FROM pg_indexes
            WHERE schemaname = current_schema()
            """
        ).fetchall()
    else:
        return set()
    return {str(row["name"]) for row in rows}


def _postgres_schema_current(conn) -> bool:
    tables = _postgres_names(conn, "table")
    if not REQUIRED_TABLES.issubset(tables):
        return False
    if OBSOLETE_TABLES.intersection(tables):
        return False
    indexes = _postgres_names(conn, "index")
    if not POSTGRES_REQUIRED_INDEXES.issubset(indexes):
        return False
    for table, required_columns in REQUIRED_COLUMNS.items():
        if not required_columns.issubset(_postgres_columns(conn, table)):
            return False
    research_chunk_columns = _postgres_columns(conn, "research_chunks")
    if research_chunk_columns.get("note_id", {}).get("is_nullable") == "NO":
        return False
    return True


def _postgres_add_column_if_missing(conn, table: str, column: str, definition: str) -> None:
    if column not in _postgres_columns(conn, table):
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {definition}")


def _postgres_drop_not_null_if_present(conn, table: str, column: str) -> None:
    columns = _postgres_columns(conn, table)
    if columns.get(column, {}).get("is_nullable") == "NO":
        conn.execute(f"ALTER TABLE {table} ALTER COLUMN {column} DROP NOT NULL")


def _migrate_postgres_db(conn) -> None:
    _postgres_add_column_if_missing(
        conn,
        "research_chunks",
        "document_id",
        "document_id INTEGER REFERENCES knowledge_documents(id) ON DELETE CASCADE",
    )
    _postgres_drop_not_null_if_present(conn, "research_chunks", "note_id")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_research_chunks_document ON research_chunks(document_id, chunk_index)")
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_research_chunks_document_unique ON research_chunks(document_id, chunk_index)"
    )

    column_migrations = {
        "job_runs": {
            "pid": "pid INTEGER",
            "heartbeat_at": "heartbeat_at TEXT",
        },
        "worker_jobs": {
            "job_run_id": "job_run_id INTEGER REFERENCES job_runs(id) ON DELETE SET NULL",
            "job_type": "job_type TEXT NOT NULL DEFAULT ''",
            "status": "status TEXT NOT NULL DEFAULT 'queued'",
            "priority": "priority INTEGER NOT NULL DEFAULT 0",
            "payload_json": "payload_json TEXT NOT NULL DEFAULT '{}'",
            "result_json": "result_json TEXT NOT NULL DEFAULT '{}'",
            "error_message": "error_message TEXT NOT NULL DEFAULT ''",
            "attempts": "attempts INTEGER NOT NULL DEFAULT 0",
            "max_attempts": "max_attempts INTEGER NOT NULL DEFAULT 1",
            "run_after": "run_after TEXT",
            "locked_by": "locked_by TEXT NOT NULL DEFAULT ''",
            "locked_at": "locked_at TEXT",
            "created_at": "created_at TEXT NOT NULL DEFAULT ''",
            "updated_at": "updated_at TEXT NOT NULL DEFAULT ''",
            "started_at": "started_at TEXT",
            "finished_at": "finished_at TEXT",
        },
        "app_events": {
            "event_type": "event_type TEXT NOT NULL DEFAULT ''",
            "payload_json": "payload_json TEXT NOT NULL DEFAULT '{}'",
            "created_at": "created_at TEXT NOT NULL DEFAULT ''",
            "published_at": "published_at TEXT",
        },
        "arxiv_papers": {
            "pdf_path": "pdf_path TEXT NOT NULL DEFAULT ''",
            "text_path": "text_path TEXT NOT NULL DEFAULT ''",
            "text_extracted_at": "text_extracted_at TEXT",
            "text_status": "text_status TEXT NOT NULL DEFAULT 'pending'",
            "text_error": "text_error TEXT NOT NULL DEFAULT ''",
            "text_char_count": "text_char_count INTEGER NOT NULL DEFAULT 0",
        },
        "paper_reader_messages": {
            "context_json": "context_json TEXT NOT NULL DEFAULT '{}'",
        },
        "matches": {
            "arxiv_chunk_id": "arxiv_chunk_id INTEGER REFERENCES arxiv_text_chunks(id) ON DELETE SET NULL",
        },
        "project_paper_matches": {
            "rank_score": "rank_score REAL NOT NULL DEFAULT 0",
            "quality_score": "quality_score REAL NOT NULL DEFAULT 0",
        },
        "research_projects": {
            "obsidian_project_path": "obsidian_project_path TEXT NOT NULL DEFAULT ''",
            "obsidian_output_dir": "obsidian_output_dir TEXT NOT NULL DEFAULT ''",
            "obsidian_note_id": "obsidian_note_id INTEGER REFERENCES obsidian_notes(id) ON DELETE SET NULL",
            "obsidian_folder": "obsidian_folder TEXT NOT NULL DEFAULT ''",
            "obsidian_status_tag": "obsidian_status_tag TEXT NOT NULL DEFAULT ''",
            "discovery_source": "discovery_source TEXT NOT NULL DEFAULT 'manual'",
            "source_tags_json": "source_tags_json TEXT NOT NULL DEFAULT '[]'",
            "arxiv_categories_json": "arxiv_categories_json TEXT NOT NULL DEFAULT '[]'",
            "automation_json": "automation_json TEXT NOT NULL DEFAULT '{}'",
        },
        "project_paper_recommendations": {
            "importance": "importance TEXT NOT NULL DEFAULT ''",
            "relation_type": "relation_type TEXT NOT NULL DEFAULT 'indirect'",
            "reason": "reason TEXT NOT NULL DEFAULT ''",
            "obsidian_path": "obsidian_path TEXT NOT NULL DEFAULT ''",
            "attachment_path": "attachment_path TEXT NOT NULL DEFAULT ''",
            "source_judgment_hash": "source_judgment_hash TEXT NOT NULL DEFAULT ''",
            "synced_at": "synced_at TEXT",
        },
        "daily_run_meta": {
            "source_job_id": "source_job_id INTEGER REFERENCES job_runs(id) ON DELETE SET NULL",
            "arxiv_batch_id": "arxiv_batch_id TEXT NOT NULL DEFAULT ''",
            "mode": "mode TEXT NOT NULL DEFAULT 'run-daily'",
            "settings_hash": "settings_hash TEXT NOT NULL DEFAULT ''",
            "searchers_json": "searchers_json TEXT NOT NULL DEFAULT '[]'",
            "embedding_model": "embedding_model TEXT NOT NULL DEFAULT ''",
            "created_at": "created_at TEXT NOT NULL DEFAULT ''",
        },
        "daily_run_steps": {
            "status": "status TEXT NOT NULL DEFAULT 'pending'",
            "started_at": "started_at TEXT",
            "finished_at": "finished_at TEXT",
            "error": "error TEXT NOT NULL DEFAULT ''",
            "meta_json": "meta_json TEXT NOT NULL DEFAULT '{}'",
        },
        "daily_run_papers": {
            "source": "source TEXT NOT NULL DEFAULT 'new_arxiv'",
            "retry_reason": "retry_reason TEXT NOT NULL DEFAULT ''",
            "published_at": "published_at TEXT NOT NULL DEFAULT ''",
            "prefilter_score": "prefilter_score REAL",
            "prefilter_rank": "prefilter_rank INTEGER",
            "prefilter_passed": "prefilter_passed INTEGER NOT NULL DEFAULT 0",
            "selected": "selected INTEGER NOT NULL DEFAULT 0",
            "selection_reason": "selection_reason TEXT NOT NULL DEFAULT ''",
            "text_status": "text_status TEXT NOT NULL DEFAULT 'pending'",
            "embedding_status": "embedding_status TEXT NOT NULL DEFAULT 'pending'",
            "global_match_status": "global_match_status TEXT NOT NULL DEFAULT 'pending'",
            "project_match_status": "project_match_status TEXT NOT NULL DEFAULT 'pending'",
            "judgment_status": "judgment_status TEXT NOT NULL DEFAULT 'pending'",
            "recommendation_status": "recommendation_status TEXT NOT NULL DEFAULT 'pending'",
            "report_status": "report_status TEXT NOT NULL DEFAULT 'pending'",
            "archive_status": "archive_status TEXT NOT NULL DEFAULT 'pending'",
            "error": "error TEXT NOT NULL DEFAULT ''",
            "updated_at": "updated_at TEXT NOT NULL DEFAULT ''",
        },
    }
    for table, columns in column_migrations.items():
        existing = _postgres_columns(conn, table)
        for column, definition in columns.items():
            if column not in existing:
                conn.execute(f"ALTER TABLE {table} ADD COLUMN {definition}")

    unique_indexes = [
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_matches_unique_paper_chunk ON matches(paper_id, chunk_id)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_user_feedback_unique_paper_status ON user_feedback(paper_id, status)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_project_notes_unique_project_note ON project_notes(project_id, note_id)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_project_context_documents_unique ON project_context_documents(project_id, document_id, relation)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_paper_sources_unique ON paper_sources(paper_id, source_type, source_identifier)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_paper_chunks_unique ON paper_chunks(paper_id, asset_id, chunk_index)",
    ]
    for sql in unique_indexes:
        conn.execute(sql)
    for sql in (
        "CREATE INDEX IF NOT EXISTS idx_worker_jobs_claim ON worker_jobs(status, priority DESC, run_after, id)",
        "CREATE INDEX IF NOT EXISTS idx_worker_jobs_job_run ON worker_jobs(job_run_id)",
        "CREATE INDEX IF NOT EXISTS idx_app_events_unpublished ON app_events(published_at, id)",
    ):
        conn.execute(sql)
    from .artifacts import migrate_legacy_artifact_tables

    migrate_legacy_artifact_tables(conn, drop_legacy=True)


def update_job_meta(
    conn: Any,
    job_id: int,
    message: str,
    meta: dict[str, Any],
) -> None:
    conn.execute(
        """
        UPDATE job_runs
        SET message = ?, meta_json = ?, heartbeat_at = ?
        WHERE id = ?
        """,
        (message, to_json(meta), utc_now(), job_id),
    )
    conn.commit()


def _parse_timestamp(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        return parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _process_is_alive(pid: int) -> bool:
    if pid <= 0:
        return False
    if pid == os.getpid():
        return True
    if os.name == "nt":
        try:
            result = subprocess.run(
                ["tasklist", "/FI", f"PID eq {pid}", "/FO", "CSV", "/NH"],
                capture_output=True,
                timeout=5,
                check=False,
            )
        except (OSError, subprocess.SubprocessError):
            return True
        output = (result.stdout or b"").strip()
        if not output:
            return False
        return str(pid).encode("ascii") in output
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def mark_stale_job_runs(
    conn: Any,
    stale_after_seconds: int = JOB_STALE_AFTER_SECONDS,
    legacy_stale_after_seconds: int = LEGACY_JOB_STALE_AFTER_SECONDS,
) -> dict[str, int]:
    now = datetime.now(timezone.utc)
    now_text = now.isoformat(timespec="seconds")
    rows = conn.execute(
        """
        SELECT id, job_type, started_at, message, pid, heartbeat_at, meta_json
        FROM job_runs
        WHERE status = 'running'
        ORDER BY id
        """
    ).fetchall()
    marked = 0
    for row in rows:
        meta = from_json(row["meta_json"], {})
        if not isinstance(meta, dict):
            meta = {}
        if meta.get("worker_job"):
            continue
        pid = int(row["pid"] or 0)
        started = _parse_timestamp(row["started_at"])
        reason = ""
        if pid:
            if not _process_is_alive(pid):
                reason = f"process {pid} is no longer running"
        elif started and now - started > timedelta(seconds=legacy_stale_after_seconds):
            reason = f"legacy running job older than {legacy_stale_after_seconds} seconds"
        if not reason:
            continue
        meta["stale"] = {
            "marked_at": now_text,
            "reason": reason,
        }
        previous_message = str(row["message"] or "").strip()
        message = f"Marked stale: {reason}"
        if previous_message:
            message = f"{message}; previous message: {previous_message[:500]}"
        conn.execute(
            """
            UPDATE job_runs
            SET status = 'failed',
                finished_at = ?,
                message = ?,
                heartbeat_at = ?,
                meta_json = ?
            WHERE id = ? AND status = 'running'
            """,
            (now_text, message, now_text, to_json(meta), int(row["id"])),
        )
        marked += 1
    if marked:
        conn.commit()
    return {"stale_jobs_checked": len(rows), "stale_jobs_marked": marked}


@contextmanager
def job_run(conn: Any, job_type: str) -> Iterator[int]:
    started = utc_now()
    cur = conn.execute(
        """
        INSERT INTO job_runs(job_type, status, started_at, pid, heartbeat_at)
        VALUES (?, 'running', ?, ?, ?)
        """,
        (job_type, started, os.getpid(), started),
    )
    job_id = int(cur.lastrowid)
    conn.commit()
    try:
        yield job_id
    except Exception as exc:
        try:
            conn.rollback()
        except Exception:
            pass
        try:
            conn.execute(
                """
                UPDATE job_runs
                SET status = 'failed', finished_at = ?, message = ?, heartbeat_at = ?
                WHERE id = ?
                """,
                (utc_now(), str(exc), utc_now(), job_id),
            )
            conn.commit()
        except Exception:
            try:
                conn.rollback()
            except Exception:
                pass
        raise
    else:
        conn.execute(
            """
            UPDATE job_runs
            SET status = 'completed', finished_at = ?, heartbeat_at = ?
            WHERE id = ?
            """,
            (utc_now(), utc_now(), job_id),
        )
        conn.commit()


@contextmanager
def existing_job_run(conn: Any, job_type: str, job_id: int) -> Iterator[int]:
    started = utc_now()
    conn.execute(
        """
        UPDATE job_runs
        SET job_type = ?,
            status = 'running',
            pid = ?,
            heartbeat_at = ?,
            message = CASE WHEN message = '' OR message = 'Queued' THEN 'Running' ELSE message END
        WHERE id = ?
        """,
        (job_type, os.getpid(), started, int(job_id)),
    )
    conn.commit()
    try:
        yield int(job_id)
    except Exception as exc:
        try:
            conn.rollback()
        except Exception:
            pass
        try:
            conn.execute(
                """
                UPDATE job_runs
                SET status = 'failed', finished_at = ?, message = ?, heartbeat_at = ?
                WHERE id = ?
                """,
                (utc_now(), str(exc), utc_now(), int(job_id)),
            )
            conn.commit()
        except Exception:
            try:
                conn.rollback()
            except Exception:
                pass
        raise
    else:
        conn.execute(
            """
            UPDATE job_runs
            SET status = 'completed', finished_at = ?, heartbeat_at = ?
            WHERE id = ?
            """,
            (utc_now(), utc_now(), int(job_id)),
        )
        conn.commit()
